# Generated by cucumber-sinatra. (2013-09-27 10:46:21 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'
require 'database_cleaner/cucumber'

DatabaseCleaner.strategy = :truncation

Capybara.app = Sinatra::Application

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

Before do
  DatabaseCleaner.start
end

World do
  ChitterWorld.new
end

After do |scenario|
  DatabaseCleaner.clean
end